sudo: required
services: 
  - docker
  
before_install:
  - docker build -t okoyeapps/docker-react -f Dockerfile.dev .

script:
  - docker run okoyeapps/docker-react npm run test -- --coverage --watchAll=false
